### ISSUE TITLE
Status of a screen can be seen with shape and colour

### ISSUE THREAD

**Issue by mandily-p** [edehr/edehr#16]
A tool for students and instructors. Not calculated by the system. Students would manually change the status of the pages they're working on to keep track of what they had completed and what needs to be done.

*Students*
If a screen has not been completed, a red X would be shown.
If a screen has been completed, a green circle would be shown.

*Instructors*
If a screen is part of an assignment a green circle would be shown.

Student completed means the page has data added to the assignment seed data. Not completed means the page shows just seed (or empty).
At this time there is no means for instructors to mark a page as marked.

**Comment by bryan-gilbert** [comment]
Parking this until it is requested as this is not normal EHR functionality.

**Comment by bryan-gilbert** [comment]
Wait for actual need
