### ISSUE TITLE
Add a directive to format date fields in dd MMM YYYY format.

### ISSUE THREAD

**Issue by mandily-p** [edehr/edehr#202]
Also, there is weird thing happening with a bunch of extra numbers and letters being added to the end of the appointment date in referrals to other disciplines page. 

![Screen Shot 2019-05-30 at 10 54 10 PM](https://user-images.githubusercontent.com/20425828/58684678-dca3cc80-832d-11e9-8cdc-ea9769c2c849.png)

**Comment by bryan-gilbert** [comment]
The referral field, like many others, has been changed to a descriptive text field where the user can say "one week ago" or something like this which is better in a simulated situation
