### ISSUE TITLE
Sort medication order page by day and time entered

### ISSUE THREAD

**Issue by mandily-p** [edehr/edehr#204]
This is an edge case, but I realized while playing around with the app that I can enter data in out of order and it will stay in that order. It would be a nice to have to display the medication orders in the order they were entered.

**Comment by bryan-gilbert** [comment]
Changed label to EHR Signin because that feature will include time based learning experience that will prevent the problem described.  Leave this issue open until fixed to show one more reason for time based records.

**Comment by bryan-gilbert** [comment]
MAR summary page sorts records
