### ISSUE TITLE
Pharmanet page

### ISSUE THREAD

**Issue by mandily-p** [edehr/edehr#278]
## User story
As a pharmacy student user,
I want to be able to access an EdEHR page similar to the professionally used Pharmanet page
So that my education can better simulate the professional workflow of a pharmacist.

## Description
**Requirements for the page need to be documented** 

## Expected behaviour
Bulleted list of functionality

## Error states/messaging
This might just be a reference to one story for a locale file with all of this within.

## Content/copy
Links, documents, text

## Styles
Any unique styles outside of the global styles. Ideally this is very minimal or even non-existent.

## Assumptions
Things like - user is connected to internet, 

## Acceptance criteria
Bulleted list to be used for QA. Might overlap with expected behaviour and error states.

**Comment by bryan-gilbert** [comment]
Closing until we get a sample Pharmanet page
