### ISSUE TITLE
Display activities on assignment page

### ISSUE THREAD

**Issue by mandily-p** [edehr/edehr#308]
## User story
As an instructor user,
I want to be able to view the activities associated with each assignment
So that it helps me recognize the relationship between the two

## Description
Assignments page table should have a column for activities that are associated with each assignment

## Expected behaviour
- Add a column for activity between `Description` and `External id`
- Table header should be `Activity`

**Comment by bryan-gilbert** [comment]
The Assignments page currently shows the number of Activities but "what is an activity?" The Courses page does not mention this term.  Confusing!
So, yes consider this idea and consider a new issue to clean up terminology.
