### ISSUE TITLE
Delete seed

### ISSUE THREAD

**Issue by mandily-p** [edehr/edehr#434]
## User story
As an admin user,
I want to be able to delete a seed
So that I can keep a clean list of seeds that I'm using

## Description
Delete functionality for seeds

## Expected behaviour/Acceptance criteria
- Warning if the seed is attached to any assignments

**Comment by bryan-gilbert** [comment]
can delete seed if not in use. Close this issue. Start by allowing delete activities which can enable delete learning object (unused) which can enable delete seed (unused)
