### ISSUE TITLE
Validation should happen after a user has entered and left a field

### ISSUE THREAD

**Issue by mandily-p** [edehr/edehr#435]
## User story
As an admin user,
I want to be able to see which fields I have entered incorrect information, or haven't entered mandatory information
So that I can make corrections before I submit the form

## Description
Validate AFTER field blur, not before.

Current view
<img width="811" alt="Screen Shot 2019-09-24 at 7 32 50 PM" src="https://user-images.githubusercontent.com/20425828/65564649-5f1a5280-df02-11e9-8636-c2dbdd41edd3.png">

**Comment by bryan-gilbert** [comment]
Augmented this with validation once editing has started.
Augmented by disabling the save button until form is valid.

One left over issue you may want addressed.  Try this.  Press create an assignment. Enter and then leave the assignment name. See the error message appear. Now enter and modify the external id. Note how the assignment field error message disappears even though it is invalid (empty)

**Comment by mandily-p** [comment]
I'm confused about why the validation doesn't work if the field is empty. Does it only check one field at a time? If so, can you set it to check all fields instead?
