### ISSUE TITLE
MAR - separate tabs for PRN and scheduled meds

### ISSUE THREAD

**Issue by mandily-p** [edehr/edehr#488]
As an instructor,
I would like to present the MAR page with separate tabs for PRN and scheduled medication administrations
Because that is the way the professional EHR's present it.

![Screen Shot 2019-12-24 at 8 15 01 AM](https://user-images.githubusercontent.com/20425828/71419691-9691bb80-2625-11ea-8238-b00aab82863e.png)

**Comment by bryan-gilbert** [comment]
![image](https://user-images.githubusercontent.com/13558676/71329980-09444f00-24df-11ea-90fe-1481fbfe6876.png)

**Comment by mandily-p** [comment]
Is it possible this round of MAR edits to get the "today" and the "summary" on one page? If we were able to do that, then the tabs on this page would be more streamlined with 2 instead of 4.

**Comment by mandily-p** [comment]
@bryan-gilbert I think there's a misunderstanding with the ticket. A new button isn't needed. Just the tabs need to be added to hold the scheduled vs PRN med orders.

**Comment by bryan-gilbert** [comment]
Have added PRN to the MAR today page.
