### ISSUE TITLE
Medication orders - Dependent fields for scheduling type

### ISSUE THREAD

**Issue by mandily-p** [edehr/edehr#493]
## Description
Progressively display form options based on previous selections. Bryan calls these `dependent fields`.

CHANGES HAVE BEEN MADE IN INPUT SPREADSHEET BUT NO LOGIC SET UP YET

## Expected behaviour/Acceptance criteria
- `Stat` and `once` needs to generate a single empty field 
- `PRN` populates 6 empty text boxes that don’t have a time prepopulated. These can’t be dropdown because they could be as specific as 20:25
- `Scheduled` populates a select box with what is displayed in the first column in the table below. What is selected will determine the times populated on the MAR

Order | Abbreviation | TImes
-- | -- | --
Once Daily AM | OD | 0900
Once daily PM | OD | 1800
Twice daily | BID | 0800; 2000
Three times daily | TID | 0800; 1600; 2200
Four times daily | QID | 0800; 1200; 1700; 2200
Every 4 hours | Q4H | 0600 ; 1000 ; 1400 ; 1800 ; 2200; 0200
Every 6 hours | Q6H | 0600 ; 1200 ; 1800 ; 2400
Every 8 hours | Q8H | 0600 ; 1400 ; 2200
Every 12 hours | Q12H | 1000; 2200
At night | HS | 2100
½ - 1hr before meals | AC | 0730; 1130; 1630
½ - 1 hr after meals | PC | 0900 ;1300 ; 1800

**Notes from Bryan**
- Allow progressive disclosure (Bryan calls this dependency) in form fields. For the pilot this is needed in the medications form. Make a ticket that breaks the schedule type into different dependent groups of form fields as a result of the user’s selection.
- The controller needs to be put over in another cell in the spreadsheet.
(This is used in immunology and the addictions bit)
- Change the name of each option to the shorthand description.

## Dependent on
#488 MAR - separate tabs for scheduled and PRN

**Comment by bryan-gilbert** [comment]
![image](https://user-images.githubusercontent.com/13558676/71329669-a2be3180-24dc-11ea-890c-c9963c12618d.png)

The 'Administration' field has four options: Scheduled, PRN, Stat, Once.
When the user selects 
- Scheduled then display select with options like BID / q12h 0800 2000
- PRN then display six empty text boxes that are to take time values: format 00:00
- Stat then display ... ?
- Once then display ...?

**Comment by bryan-gilbert** [comment]
Only need to work on the Stat. which is mentioned in https://github.com/edehr/edehr/issues/496
