### ISSUE TITLE
Medications order - separate tabs for PRN and scheduled meds

### ISSUE THREAD

**Issue by mandily-p** [edehr/edehr#497]
## User story
As an instructor user,
I want to be able to split the PRN and scheduled (schedule, once, stat) into two separate tabs on the medications order
Because this is how the professional applications do it and we want to train our students to remember to look for the second tab/page. (yes, we know this isn't as intuitive)

## Description
PRN medications should appear in a second tab on the medications page. (Similar to the vital signs tabs)

## Expected behaviour/Acceptance criteria
- Each tab has it's own table
- Each tab has it's own button to add to the table

Use the same styles as what's been used on the Vital signs page.

![Screen Shot 2019-12-24 at 8 06 57 AM](https://user-images.githubusercontent.com/20425828/71419753-09029b80-2626-11ea-9e8d-04f195034d52.png)

![Screen Shot 2019-12-24 at 8 07 58 AM](https://user-images.githubusercontent.com/20425828/71419746-f720f880-2625-11ea-81ea-775ade05534a.png)

**Comment by bryan-gilbert** [comment]
PRN is done
