### ISSUE TITLE
Setting page status

### ISSUE THREAD

**Issue by mandily-p** [edehr/edehr#54]
A dropdown for status options is shown to the right side of the page title bar
If a screen is not complete, the dropdown is set to "Incomplete"
Users can manually change the dropdown value.

All options:
Incomplete (red)
No information available (green)
Up to date (green)
Complete (green)

The status of the page is also displayed with a coloured icon beside each item in the left nav

**Comment by bryan-gilbert** [comment]
Parking this pending a strong business case. Many stakeholders like to openness of the app as it is because the student needs to act in a real life manner.
