### ISSUE TITLE
Manage consumer information

### ISSUE THREAD

**Issue by bryan-gilbert** [edehr/edehr#562]
## User story
As a EHR administrator user,
I want to be able to manage  LTI consumer
Because  
I need to be able to save all information related to a give consumer, 
I need to be able to remove all information related to a given consumer
I need to be able to recreate the consumer from the saved information

## Description
Extract and restored information related to a single consumer

Step 1. Add a button to the /consumers page beside each consumer. When pressed download a json file structured with 

consumer :  the consumer record from the db,
users : [ list of user records ],
activities: [ list of activity records ],
 to be continued

**Comment by viniciusarre** [comment]
That's an interesting idea. Wouldn't there be a security issue if/when exposing too much data?
