### ISSUE TITLE
QuotaExceededError: Dom exception 22:

### ISSUE THREAD

**Issue by bryan-gilbert** [edehr/edehr#74]
### Description 
When using the EdEHR on iOS iPad you may encounter this error message: "QuotaExceededError: Dom exception 22"

EdEHR is using javascript local storage and this does not work in iOS Safari private mode. You can not use EdEHR with private mode.   See this page for instructions on how to switch between modes:
https://www.imore.com/how-use-browser-tabs-safari-iphone-and-ipad#private

**Comment by mandily-p** [comment]
@bryan-gilbert Do we need to do anything about this, or can we close this issue?
