### ISSUE TITLE
Sticky footer on short pages

### ISSUE THREAD

**Issue by mandily-p** [edehr/edehr#79]
The footer should stick to the bottom of the viewport when the page content doesn't fill the screen.

I couldn't figure out how to edit the html/pug to do this :)

Here's what I'd like to do:

html
```
<body>
  <div class="app">
    content
  </div>
  <footer></footer>
</body>
```

```
html, body {
  height: 100%;
}
body {
  display: flex;
  flex-direction: column;
}
.app {
  flex: 1 0 auto;
}
footer {
  flex-shrink: 0;
}
```

All that being said - I'm not sure how your debugging stuff plays with this :)

**Comment by bryan-gilbert** [comment]
We have sticky footers in the dialogs. 
We have sticky header showing important patient data.
Marking as done until some guidance comes as to which content needs to stick to the footer.
