### ISSUE TITLE
docker-compose requirement

### ISSUE THREAD

**Issue by iamalonso** [edehr/edehr#979]
## User story
As a student of medical informatics user,
I want to be able to install edEHR trough Docker Compose
Because  it is a portable solution for the different operating systems of our data center.

## Description
Add the docker-compose file to build the entire system.

**Comment by bryan-gilbert** [comment]
See the /deployment directory

**Comment by iamalonso** [comment]
> See the /deployment directory

Thanks @bryan-gilbert for your information
I'm gonna try your suggestion
